title: Muhammad Fadli Irjiyansyah
url: https://www.linkedin.com/in/fadliirjiyansyah/
logo: Assets/Profile-Linkedin.png
description: Linkedin
url: https://www.linkedin.com/in/fadliirjiyansyah/
show_downloads: true
theme: jekyll-theme-minimal
