title: Muhammad Fadli Irjiyansyah
url: https://www.linkedin.com/in/fadliirjiyansyah/
logo: Assets/Profile-Linkedin.png
logo: Assets/Linkedin--Logo.png
url: https://www.linkedin.com/in/fadliirjiyansyah/
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
