title: Muhammad Fadli Irjiyansyah
logo: Assets/Profile-Linkedin.png
linkedin: https://www.linkedin.com/in/fadliirjiyansyah/
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
